language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  
sudo: false
before_script: cd Java/OpenmlWeka 
script: ant -buildfile build_package.xml make_package -DpackageName=OpenmlWeka
after_script: ant -buildfile build_package.xml test